#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SM_TrapCage01_Closed_DMBP

#include "Basic.hpp"

#include "SM_TrapCage01_Closed_DMBP_classes.hpp"
#include "SM_TrapCage01_Closed_DMBP_parameters.hpp"


SDK_NAMESPACE_START

// Function SM_TrapCage01_Closed_DMBP.SM_TrapCage01_Closed_DMBP_C.FireImpulse
// (Public, BlueprintCallable, BlueprintEvent)

void ASM_TrapCage01_Closed_DMBP_C::FireImpulse()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_TrapCage01_Closed_DMBP_C", "FireImpulse");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
