#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SM_TrapCage01_Closed_DMBP

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass SM_TrapCage01_Closed_DMBP.SM_TrapCage01_Closed_DMBP_C
// 0x0018 (0x02C8 - 0x02B0)
class ASM_TrapCage01_Closed_DMBP_C final : public AActor
{
public:
	class UDestructibleComponent*                 Destructible;                                      // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Scene;                                             // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ARadialForceActor*                      RadialForce;                                       // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void FireImpulse();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SM_TrapCage01_Closed_DMBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SM_TrapCage01_Closed_DMBP_C")
	}
	static class ASM_TrapCage01_Closed_DMBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASM_TrapCage01_Closed_DMBP_C>();
	}
};
DUMPER7_ASSERTS_ASM_TrapCage01_Closed_DMBP_C;

SDK_NAMESPACE_END
