#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace bG_Gauntlet_Arm_ABP { struct FAnimBlueprintGeneratedConstantData; }

namespace HooKTestABP { struct FAnimBlueprintGeneratedConstantData; }

namespace SM_DropPodAnimated_01_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace ENV_VEG_Bush_HidingBushBP { class AENV_VEG_Bush_HidingBushBP_C; }

namespace ENV_VEG_Bush_HidingBushBP_0 { class AENV_VEG_Bush_HidingBushBP_C; }

namespace H_Gauntlet_Arm_ABP { struct FAnimBlueprintGeneratedConstantData; }


namespace HuntressABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace HookABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace FalconABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace NewGuyABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace WingsABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace RedDeerABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}
